version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./www.conf:/etc/nginx/nginx.conf
      - /Users/bob/dev/lizhi-api:/var/www/html
    depends_on:
      - php
    networks:
      - web_net
  node16:
    image: node:16
    volumes:
      - /Users/bob/dev/lizhi-api:/var/www/html
    command: sh -c "npm config set registry https://registry.npmmirror.com && tail -f /dev/null"
    networks:
      - web_net
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /Users/bob/dev/lizhi-api:/var/www/html
    command: php-fpm
    ports:
      - "9000:9000"
    environment:
      PHP_IDE_CONFIG: serverName=lizhijun-server
    networks:
      - web_net

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Lrdxsadf12
      MYSQL_DATABASE: base
      MYSQL_USER: lizhijun
      MYSQL_PASSWORD: Lrdxsadf12
    volumes:
      - ./mysql_db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql_db/data:/var/lib/mysql

  redis:
    image: redis:7.0.15
    container_name: web_redis
    ports:
      - 6379:6379
    volumes:
      - ./redis_db:/data
    networks:
      - web_net
    command: ['redis-server', '--requirepass', 'lizhijun', '--appendonly', 'yes']

networks: 
  web_net:
    driver: bridge

volumes:
  data:
    driver: local
